# Notebook-related checks

name: Presubmit checks

on:
  # Relevant PRs
  pull_request:
    paths:
    - "google/**"
    - "tests/**"
  # Allow manual runs
  workflow_dispatch:

jobs:
  test3_11:
    name: Test Py3.11
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Run tests
      run: |
        python --version
        pip install -e .[dev]
        pip show google-ai-generativelanguage
        pip show google-generativeai
        python -m unittest discover --pattern '*test*.py'
  test3_10:
    name: Test Py3.10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run tests
      run: |
        python --version
        pip install -e .[dev]
        pip show google-ai-generativelanguage
        pip show google-generativeai
        python -m unittest discover --pattern '*test*.py'
  test3_9:
    name: Test Py3.9
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Run tests
      run: |
        python --version
        pip install -e .[dev]
        pip show google-ai-generativelanguage
        pip show google-generativeai
        python -m unittest discover --pattern '*test*.py'
  pytype3_10:
    name: pytype 3.10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run pytype
      run: |
        python --version
        pip install -e .[dev]
        pip show google-ai-generativelanguage
        pip show google-generativeai
        pip install gspread ipython
        pytype
  format:
    name: Check format with black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Check format
      run: |
        python --version
        pip install black
        black . --check

